version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: besta-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: besta-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8
    container_name: besta-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: besta
      MYSQL_USER: bestauser
      MYSQL_PASSWORD: bestapass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mongo_data:
  redis_data:
  mysql_data: